language: node_js
sudo: false
node_js:
- '7'
- '6'
- '5'
- '4'
notifications:
  email: false
  slack:
    secure: KUq52OF6wV+uHgsFk6ljEbQGNSO6vv1j7sX/RH2bdphF9YBH+QIHh4MuaYztGIZtpVu635oMW94XruBbB7tlQdolk0LoZ+MO7jH+bualXIu1YlegGmwIosLT4suU+PRdWH4oROjU7FPvXHLoQcmY9m5S80IJvc+aNnuPOnhI2eQ3qGOKZMKzwvB8aX/yZLF2Guj7kUydoE+E/A+UOyJxNd+Mn0IpsGE03lGcJvW8WY8RkcyAWrbf9uA2RzQN10iM4bSUqJNlPmYGA7xpQeo2Pgz6atL50kM259L9uMH9eBf1Q5d5oVJ+E6bcQL1dIIIQ6CXllIAFywDBGiFPt8TPusmQ2ChGMM5sZa+4SP6dLfuth3MzlAocBMSvGm41T8tl94O8rHdFyb+tI8+Ja+HEWyJlGjmuxpxpHHCtHwzJdJ8EDq18VSMUzAc2n05NHZK4j+S2a+xk+chcaBxQGMWozBaFM2Gn0I+YQaKUNmbbmOest+vec9WzOVGayjwaWXrb7eK4Wd3cSmry+r9y6bCGcLGcHhn4QSCNzLyDvi8WjTRzkOVOsWwNEZIH3Fcyp7UErSXF83mduHY4hlomOC57iMhA1em1Ytnq0L1N+BwmflTdxRIXj6EbFFieSI4a96ZiKWpTPmJWPQ2d9n970/SZyPGV6heJse6t8EWOQNG29xw=
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
